### ISSUE TITLE
'2024'in titel

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#101]
(bron: Review 04-okt-2024)

Het heeft mijn voorkeur om het jaartal 2024 mee te nemen in de titel ‘Startanalyse PBL 2024’.

Nu:
![Image](https://github.com/user-attachments/assets/b5287703-e4da-429d-a3f1-25a0bc863149)

**Comment by baasgeo** [comment]
Titel is aangepast zoals voorgesteld
