### ISSUE TITLE
Eenheden in locatie informatie LN

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#111]
Denk aan eenheden m^3 kwh ipv GJ (algemeen herkenbare eenheden)
mogelijke implementatie door links vanuit Feature Info naar begrippen-pagina-onderdeel.

**Comment by MaartenHilferink** [comment]
Begrippenlijst:
- MT
- LT
- GJ

**Comment by eoudejans** [comment]
Html templating voor locatie informatie Geimplementeerd:
![Image](https://github.com/user-attachments/assets/3e8cb88b-c801-417e-b190-f24c76187aad)

Eenheden kunnen nu beter weergeven worden.

**Comment by eoudejans** [comment]
Eenheden staan voor alle strategieen + de LN kaartbladen in de locatie informatie:
![Image](https://github.com/user-attachments/assets/ef24d25b-ca75-48b8-a30f-4c05b6754641)
