### ISSUE TITLE
Verdachte data tegen in Performance.csv

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#137]
Tijdens bisecten komen we verdachte data tegen in Performance.csv:

![image](https://github.com/user-attachments/assets/3e4c90f8-edec-4540-8ba1-8bf5f0b65d9b)

Een rendement van "70%" zal als 70 worden ingelezen, dan is de metervraag = functionele vraag / rendement dus 100x kleiner dan bedoeld.

**Comment by poorthuis-w** [comment]
Goed opgemerkt. Dit is in een latere commit verbeterd naar goed leesbare input.
