### ISSUE TITLE
Euro/tonCO2 -> €/ton CO_2

### ISSUE THREAD

**Issue by poorthuis-w** [ObjectVision/SAVI2#138]
woning -> WEQ of weq of Weq

**Comment by poorthuis-w** [comment]
De berekening is [euro/jaar] / [ton CO2/jaar]. Daar komt dus de eenheid [euro/ton CO2] uit. 

Daarnaast korten we woningequivalenten af naar "weq". Allemaal kleine letters.

**Comment by MaartenHilferink** [comment]
Ondanks de twijfel, t.g.v. de ordegrootte, bevestig ik de bevinding dat €/jaar wordt gedeeld door tot CO_2/jaar.
