### ISSUE TITLE
Javascript in templates mogelijk maken

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#141]
Huidige syntax voor locatie-info template bevat $ als marker voor data-field placeholders. Dit conflicteert met het kunnen opnemen van JavaScript, wat o.a. nodig is om Energielabels en Gebruiksdoelen goed te kunnen weergeven.

deze oplossing valt af te wegen tegen server-size (pre) renderen.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the template to use {{ }} instead of $ for data field placeholders. This allows for including JavaScript without conflicts.

You can review changes in this commit: https://github.com/lkilu6456546/ObjectVision-SAVI2-141/commit/8bbf349b2a76882af4903be8927bfad3fd71a7cf.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by baasgeo** [comment]
Voor het parsen van de placeholders wordt gebruikt gemaakt van template literals. Dit is javascript native (es6) functionaliteit waardoor het parsen snel gaat maar ook altijd valide & secure is voor de browser. Hierdoor is het minder kwetsbaar voor veelvoorkomende webhacks zoals cross-site scripting (XSS).

Binnen een template literal wordt elke geldige JavaScript-expressie - wanneer deze is omgeven door ${} syntaxis -geëvalueerd en de resulterende waarde getoond in de string.

Dit maakt het mogelijk om eenvoudige berekeningen uit te voeren in de template:
``` js
console.log(`Fifteen is ${a + b} and not ${2 * a + b}.`); 
```

Functies uit te voeren:
``` js
console.log(`Naam: ${name.toLowerCase()}`); 
console.log(`Base64: ${btoa('1234')}`);
```

Of vergelijkingen uit te voeren:
``` js
console.log(`Groot: ${fieldName > 12 ? 'Ja' : 'Nee'}`);
```

Info: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Het is dus mogelijk om simpele functies of berekeningen op te nemen binnen een template literal. Complexe berekeningen zou ik inderdaad server-side berekenen. Dit kun je doen door de berekende waarde in een apart veld op te nemen en hier naar te verwijzen in de template.
