### ISSUE TITLE
Template aanpassingen

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#142]
![Image](https://github.com/user-attachments/assets/6d18186b-8ccc-423b-8c7e-5036831134ea)

Warmteverbruik (H07) [GJ/hectare] -> Dichtheid warmteverbruik (H07) [GJ/ha/jaar]
en onder CO2 uitstoot (H15).

H01 eenheid ->: GJ/WEQ/jaar

"tonCO2" -> "ton CO2"

naast aantall woningen  ook aantal utiliteiten en aantal woning equivalenten [WEQ]

![Image](https://github.com/user-attachments/assets/44d0d7f7-fb30-4054-b7e3-a9c4dc04f06e)

![Image](https://github.com/user-attachments/assets/8a35aa0e-432c-4bd2-b3f5-af0a29ef7bc5)

**Comment by MaartenHilferink** [comment]
Vereist #144

**Comment by MaartenHilferink** [comment]
Bij variant een betere omschrijving weergeven:

![Image](https://github.com/user-attachments/assets/178e593d-6708-4ee7-a3b6-c23afbb22e00)

![Image](https://github.com/user-attachments/assets/21e12e30-4c9a-46e0-929b-27d87f7161d4)

![Image](https://github.com/user-attachments/assets/3ef2a3ab-529c-4615-814f-167737da3947)

![Image](https://github.com/user-attachments/assets/1f112df2-e8f0-4df2-8699-ed6f7267dba4)

**Comment by eoudejans** [comment]
Changed template accordingly:
![Image](https://github.com/user-attachments/assets/cb39112f-3fe7-4b82-b9d2-ee37be700060)
