### ISSUE TITLE
LN legenda label voorstellen

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/SAVI2#152]
![Image](https://github.com/user-attachments/assets/9ce6cb8f-8bfd-454c-a3d1-c278df37b00b)

Voorstel:
"Geen bebouwing en/of door..."  -> "Geen doorrekening"

![Image](https://github.com/user-attachments/assets/0e2baa92-7107-4511-8d0c-3af771bc5fae)

Voorstel:
"Leveringscomponenten" -> 'Warmtedragers"

**Comment by eoudejans** [comment]
UPDATE data.layers
SET mapstyle = REPLACE(mapstyle::TEXT, 'Geen bebouwing en/of doorrekening', 'Geen doorrekening')::JSONB;

**Comment by MaartenHilferink** [comment]
![Image](https://github.com/user-attachments/assets/544f9a69-4901-4e70-94f3-3aec58e2e509)

**Comment by poorthuis-w** [comment]
@eoudejans graag zou ik leveringscomponenten gelijk houden. Dan blijft de link met levering totaal duidelijk, en blijft de structuur hetzelfde als bij verbruik totaal en verbruikscomponenten.

**Comment by eoudejans** [comment]
@poorthuis-w ik zal de leveringscomponenten houden zoals ze zijn.

**Comment by eoudejans** [comment]
Verder heb ik Geen bebouwing en/of doorrekening vervangen door Geen doorrekening, korter en dekt nog steeds de lading:
![image](https://github.com/user-attachments/assets/f7277109-4f09-438c-993e-93af687c7b03)
