### ISSUE TITLE
Check ook of S3g wel goed is uitgerekend,; een afgiftetemperatuur van 15(o) is toch niet genoeg voor label D woningen?

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#155]
Zou S3g niet beter WKO15_50 of LT30_50 of LT30_30 moeten zijn ?
![Image](https://github.com/user-attachments/assets/3c5e560b-a7c6-46d3-8828-dda60957609e)

**Comment by poorthuis-w** [comment]
Hoi Maarten,

De twee temperaturen in de varianten zijn de (laagst mogelijke) brontemperatuur en de aanlevertemperatuur. Als de aanlevertemperatuur te laag is om een vbo mee te verwarmen, wordt en individueel opgewaardeerd. Dit gebeurt met een inpandige warmtepomp. Tot op welk temperatuursniveau wordt opgewaardeerd hangt wel af van de isolatiekwaliteit, maar die verschilt per object. Daarom heb ik er voor gekozen om in de variant alleen de generieke temperaturen, bron en aanlever, te zetten.

Groet,
Wessel
