### ISSUE TITLE
Performance traag bij heel veel kaartlagen

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#16]

**Comment by eoudejans** [comment]
![image](https://github.com/ObjectVision/SAVI2/assets/96182097/1a28a7de-48ae-4f19-a1eb-a56faba36e22)

**Comment by MaartenHilferink** [comment]
4.5 GB voor 12 kaartlagen ?  
1 strategie is 100 MB in .pbf = 6kb per buurt = 750 bytes per buurt per zoom-level) kan vast ook minder met betere simplificatie, maar belangrijker is een passend datamodel, dus
- attribuut values maar 1x per buurt en niet voor ieder zoomlevel

In browser, client-side lijkt iedere kaartlaag de hoeveelheid memory te snel te verhogen; hier is ook datamodel waarschijnlijk de bepalende factor:
- geometrie is (per zoom-level) gelijk voor alle kaartlagen.

**Comment by MaartenHilferink** [comment]
Zie ook workaround by #17

**Comment by baasgeo** [comment]
MapGallery maakt per vector tile source een nieuwe [source](https://maplibre.org/maplibre-style-spec/sources/), dit verklaart de toename van het geheugen gebruik. Dit vraagt een correctie aan de applicatie.

**Comment by MaartenHilferink** [comment]
See details at #24, fixed.
