### ISSUE TITLE
Selectie boundingbox lijkt gerelateerd aan scherm geometrie

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/SAVI2#160]
Ik zoom ver in op bijvoorbeeld de volgende kaart: https://kaartviewer.asa2024.nl/app/map/main/111/info. Dan klik ik op een gebied om informatie op te vragen. Vervolgens zoom ik uit en zie ik deels de gebiedsgrenzen en deels de rechte lijnen van het ingezoomde gebied:

![image](https://github.com/user-attachments/assets/7f14645f-fbca-4b6c-afd0-593cd4a19158)

**Comment by baasgeo** [comment]
Dit is inderdaad een beperking van vector tiles. Alleen de tiles van het ingezoomde gebied worden opgevraagd. Wanneer een polygon groter is dan het ingezoomde gebied, wordt alleen de geometrie binnen de tile weergegeven. Mocht er een manier zijn om via een vector tile de originele, volledige data op te halen, dan hoor ik dat graag. Voorlopig lijkt dit een technische beperking te zijn.
