### ISSUE TITLE
Bij keuze voor een collection (zoals Sn) zijn alle kaartlagen meteen AAN, max 1 zou aan moeten staan.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#17]

**Comment by MaartenHilferink** [comment]
WORKAROUND: bij openen van een nieuwe collectie eerst klikken op "Kaartlagen"-> uitzetten, en dan per gewenste kaartlaag-klasse weer aanzetten.



![Image](https://github.com/ObjectVision/SAVI2/assets/2284361/82205907-bd05-4e62-b795-dfdd6dd0137f)

**Comment by baasgeo** [comment]
Dit is gefixed in MapGallery versie 7.2. De beheerder kan voor een collectie aangeven of een kaartlaag aan/uit staat en of de legenda uitgeklapt/ingeklapt is. 

Ik heb de docker voor de PBL viewer op de developer tag gezet.
