### ISSUE TITLE
Keyfocus kwijt bij kaartlaag toevoegen

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#170]
![Image](https://github.com/user-attachments/assets/f9c14751-c09a-4540-b1e2-bd1a9ce03059)

Als ik rechts op "Kaarlagen"->"Kaartlaag toevoegen" klik, dan verschijnt:

![Image](https://github.com/user-attachments/assets/40ba43bb-94f4-41ce-9196-4b8f411f195c)

Als ik ga tikken, komen keys niet aan bij het tekstvak [filteren...] dat visueel wel de indruk geeft de key-focus te hebben, en dat zou qua work-flow ook logisch zijn.

Gewenst gedrag: tekstvak [filteren...] de key-focus laten krijgen zodra de popup "Kaartlaag toevoegen" op popt.

**Comment by baasgeo** [comment]
Goed gevonden, ik heb deze direct aangepast, zie ook commit https://github.com/mapgallery/webapp/commit/7e1681183a6bd893d60cb502c18f0372d7ccf2bc
