### ISSUE TITLE
Aanbod data (point + line) ook opnemen

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#18]

**Comment by MaartenHilferink** [comment]
TEO (Thermische Energie uit Oppervlaktewater):

![Image](https://github.com/ObjectVision/SAVI2/assets/2284361/383e5dd5-5841-48f1-9cf5-61edc3d91d51)


WKO (Warmte Koude Opslag):

![Image](https://github.com/ObjectVision/SAVI2/assets/2284361/08fb271c-fd1b-4cd6-80a3-8215d9369e55)



Geothermie:


![Image](https://github.com/ObjectVision/SAVI2/assets/2284361/8208e5b5-2052-4890-bb0e-66c758c3dff5)


![Image](https://github.com/ObjectVision/SAVI2/assets/2284361/4f3a59f7-e417-47a8-89a7-1e63c2a80f62)



Gas:


![Image](https://github.com/ObjectVision/SAVI2/assets/2284361/b18c3c97-3c89-4802-804a-c0dea8d29101)

**Comment by MaartenHilferink** [comment]
Klimaatkaarten
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/6d240dc7-2f20-407b-a889-0077a68c2f95)
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/67e1959b-c9bc-4cb1-bd05-b322f9444f65)
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/336954f3-c5ad-4f21-a9e1-096b40963994)
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/9c8ca02f-9b9b-4769-bdc0-7a206b5fa62e)
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/9bbc1136-126c-4b97-a178-64f7c61d5eef)

**Comment by MaartenHilferink** [comment]
Warmtenet leidingen

![Image](https://github.com/ObjectVision/SAVI2/assets/2284361/a780dceb-d414-4844-b704-f9b73270cd30)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/a537320b-5c9f-4f0f-81a2-ffd9676eef00)

**Comment by MaartenHilferink** [comment]
Warmtenet gebieden ?
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/481b5cc9-218d-4655-9e7a-e6d1b915e9af)

**Comment by eoudejans** [comment]
TEO, WKO

**Comment by eoudejans** [comment]
Geothermie

**Comment by eoudejans** [comment]
Initiele implementatie klimaat kaarten:
![image](https://github.com/user-attachments/assets/49154ad3-c78f-4357-b78d-2a509f71e740)
