### ISSUE TITLE
buurt-gaten opvullen met 'grijs' nodata, ook in de legenda.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#19]

**Comment by MaartenHilferink** [comment]
@baasgeo hoe moeten we dit invullen om gaten in de kaart als grijs op te vullen ?
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/5f35822d-9120-4aa5-b1dc-cef7fb8ed30b)

**Comment by eoudejans** [comment]
Zie gaten rond bijvoorbeeld Flevoland:
![image](https://github.com/ObjectVision/SAVI2/assets/96182097/155b4319-5751-457e-8188-3951ea4a9153)

**Comment by baasgeo** [comment]
Tjsa, dat is een leuke. Voor zover ik weet zijn er geen has of isNull [functies voor geostyler](https://geostyler.github.io/geostyler-style/docs/master/modules.html).

Een extra rule zonder filter werkt wel, al voelt dat wel als een workaround

```
{
  "name": "2.1 Nationale kosten t.o.v. referentie 2030 (Euro/ton CO2)",
  "rules": [
    {
      "name": "NULL",
      "symbolizers": [
        {
          "kind": "Fill",
          "color": "gray",
          "outlineColor": "black",
          "outlineWidth": 0.3,
          "outlineOpacity": 0.7
        }
      ]
    },
    {...}
  ],
  "metadata": {
    "mapbox:ref": {
      "sources": {},
      "sourceLayerMapping": { "strat1": [0, 1, 2, 3, 4] }
    }
  }
}

```

**Comment by baasgeo** [comment]
![image](https://github.com/ObjectVision/SAVI2/assets/1308903/cf192dcf-16c7-4b60-b141-826bbe59dcb5)

**Comment by eoudejans** [comment]
Ah super @baasgeo daar zaten we gister naar te zoeken. We hebben een andere workaround gebruikt namelijk nulls geencodeerd, maar als dat niet nodig is heeft dat mijn voorkeur.

**Comment by eoudejans** [comment]
Al gaat daarmee alles grijs worden bij het uitvinken in de legenda van overige klassen denk ik @baasgeo?

**Comment by baasgeo** [comment]
Ja dan wordt alles grijs dus geen fijne oplossing

**Comment by eoudejans** [comment]
Oke dan houden we het bij encodering, zie: https://kaartviewer.asa2024.nl/app/map/main/101?center=5.490505570934374;52.35306635602353&zoom=9&layerIds=143;110

**Comment by MaartenHilferink** [comment]
Nu zie ik in de LN kaart de buurten met stategiecode=9999 ineens als oranje, de kleur van S5 ?
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/7e750d07-cabc-4ae5-91e8-abe5f997411f)
