### ISSUE TITLE
Ontbrekende tegels

### ISSUE THREAD

**Issue by baasgeo** [ObjectVision/SAVI2#23]
Op verschillende zoom levels ontbreken vector tiles, MapGallery geeft in de console een 404 error. Op de file server /var/tiles/layers komen de bestanden niet voor. 

Voorbeeld:
https://tiles.asa2024.nl/layers/strat2/8/130/83.pbf
https://tiles.asa2024.nl/layers/strat2/9/265/170.pbf
https://tiles.asa2024.nl/layers/strat2/14/8420/5362.pbf

**Comment by eoudejans** [comment]
![image](https://github.com/ObjectVision/SAVI2/assets/96182097/77d5d983-ccd9-4d14-a2f0-f981f3d62857)

Dit is de meest recente set, zoom level 8, lijkt me compleet. Zou het extent niet goed meegegeven zijn en dat daarmee de server denkt tiles te kunnen opvragen die er in werkelijkheid niet zijn?

**Comment by baasgeo** [comment]
Gefixt via een aanpassing aan de nginx configuratie

```
    location ~* .(pbf)$ {
            limit_except GET HEAD { deny all; }
            add_header 'Access-Control-Allow-Origin' "$http_origin";
            try_files $uri $uri/ =204;
    }
```
