### ISSUE TITLE
(Stress) TILEJSON testset maken BAG panden + bouwjaar + verblijfsobjecten + energielabel in test collectie

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/SAVI2#24]

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/67587430-998d-4719-a11b-c347eea44264)

**Comment by MaartenHilferink** [comment]
In https://dh.wzwkaart.nl/app/map/3 blijft memory rond de 50 MB.

**Comment by eoudejans** [comment]
https://kaartviewer.asa2024.nl/app/map/main/101?center=6.026266217058492;53.26871641815899&zoom=10&layerIds=213;207;110

![image](https://github.com/ObjectVision/SAVI2/assets/96182097/7b5502da-ed08-48e8-80af-b67c1a34f240)

Twee TILEJSON kaartlagen nemen ~800 MB geheugen in beslag

**Comment by eoudejans** [comment]
Veel instanties van JSArrayBufferData
![image](https://github.com/ObjectVision/SAVI2/assets/96182097/22e8d5a0-4ae1-4817-9685-1d8458c94332)

**Comment by baasgeo** [comment]
Volgens mij is dit deels hetzelfde probleem als #16: MapGallery maakt per vector tile source een nieuwe [source](https://maplibre.org/maplibre-style-spec/sources/) aan, dit verklaart de toename van het geheugen gebruik. Dit vraagt een correctie aan de applicatie.

Daarnaast kan ik me voorstellen dat raster tiles (voorgerenderde png's) uiteindelijk minder geheugen vragen dan vector tiles.

**Comment by MaartenHilferink** [comment]
We hebben onderzocht of meerdere layers met dezelfde geometrie dit probleem veroorzaakten, maar die hypothese moesten we verwerpen aangezien ook bij 2 kaartlagen met verschillende geometrie het geheugen al onverklaarbaar hoog is. Zie bijvoorbeeld: https://kaartviewer.asa2024.nl/app/map/main/101/info?center=5.831843573965216;51.94794923420369&zoom=8&layerIds=213;207;110
Ik denk dat GeoJSON / vector tiles uiteindelijk efficiënter in geheugengebruik zouden moeten zijn dan raster data, maar het lijkt er op (hypothese 2) dat de garbage collector of een reusable blob cache genaamd JSArrayBufferData ooit is ontwikkeld voor fixed size png-data en nu is hergebruikt voor variable sized vector tile data hetgeen retentie van bijna alle memory allocaties veroorzaakt. Of, een andere oorzaak wat wellicht enkel nadere diagnose en fixen behoeft, of herontwikkeling van libre-maps.

Ik stel voor straks even te overleggen om fallback opties te bespreken en wanneer we daar dan een knoop over moeten door hakken. 
- implementatie met raster tiles conform wzwkaarviewer
- alleen bij inzoomen data tone. 

Zie ook https://github.com/orgs/ObjectVision/projects/16

**Comment by baasgeo** [comment]
Zou het misschien aan de tiles zelf kunnen liggen?

Ter vergelijk heb ik twee kaartlagen uit de [Martin tile server](https://github.com/maplibre/martin) toegevoegd, _Wijken 2022 TEST_ en _Buurten 2022 TEST_. 

Wanneer beide kaartlagen zijn toegevoegd, komt het geheugengebruik uit op 133 MB, dat lijkt me acceptabel.

![image](https://github.com/ObjectVision/SAVI2/assets/1308903/bfa5713d-329c-4c8c-a6d2-d9ada5d7544d)

**Comment by MaartenHilferink** [comment]
Hoe groot was de CBS buurtkaart .shp en gerelateerde vector tiles op de Martin tile server ?

Wellicht was daar al geometry gesimplified, wat we bij ASA2024 ook nog wel verder willen doen, maar dan blijft er een (te) grote factor tussen brondata en geheugengebruik hetgeen aannemelijk maakt dat het datamodel niet past en/of de caching / garbage collection ergens op fout loopt. 

Bij ASA2024 was Buurt.shp ongeveer 80 MB ?), in verctor tiles: XXXX (@eoudejans ?); resultaat in viewer zonder gaspijpen: 500 MB, en wellicht oplopend.

**Comment by baasgeo** [comment]
Dit zijn de standaard CBS shapes (geometrie en ca. 40 velden met data), dat zal ook rond de 80 MB liggen. Het is rechtsreeks in postgis gezet, zonder conversie of simplificatie. Martin server doet [een realtime conversie](https://www.crunchydata.com/blog/dynamic-vector-tiles-from-postgis) via de postgis functies [ST_AsMVTGeom](https://postgis.net/docs/ST_AsMVTGeom.html) en [ST_AsMVT](https://postgis.net/docs/ST_AsMVT.html). Even bellen?

**Comment by MaartenHilferink** [comment]
Bij alleen OSM achtergrondlaag en uitzoomen zijn de volgende JSArrayBufferData geregistreerd:
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/f7b5b74f-89af-4074-bc81-a017293a57e1)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/738f6630-c66b-4649-9c05-341d4c6aa2a4)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/cb733bc0-567e-43e5-a821-4d84b13e5ccf)

**Comment by MaartenHilferink** [comment]
Hee, probleem lijkt ineens opgelost:
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/52651df3-5554-4d9b-953f-e3cdfa5339a6)

**Comment by MaartenHilferink** [comment]
BTW, op welk schaalniveau wordt er voldoende gesimplified. Links is OK, 2e zou als 1e moeten zijn, zelfs na enorm inzoomen liever de eerste gesimplifyde versie dan een gecrashde telefoon.

![image](https://github.com/ObjectVision/SAVI2/assets/2284361/9c304511-d351-443e-a084-0256ec4eb869)
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/5baa9b4a-18f7-457e-acc8-301ad8c949dc)

![image](https://github.com/ObjectVision/SAVI2/assets/2284361/8456fd86-abe1-49d3-b455-8d6aaed17b62)

**Comment by MaartenHilferink** [comment]
Maar op dit zoom-niveau (kennelijk zonder simpliciatie als ik naar de Friese kust scroll):

![image](https://github.com/ObjectVision/SAVI2/assets/2284361/f6452ba2-0570-42ca-bd50-c7f88943c26a)

**Comment by MaartenHilferink** [comment]
Ter vergelijking: 3d tiles in Google Maps:
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/29808b19-8696-40dc-be87-faf78ea37b67)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/7c41a57a-e8b2-458a-83b5-6ffc325533f6)
