### ISSUE TITLE
Overzicht toe te voegen kaartlagen + prioritering

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/SAVI2#25]
De 2020 viewer https://themasites.pbl.nl/leidraad-warmte/2020/# bevat vele kaartagen.  

In de 2024 viewer zijn nu een aantal lagen opgenomen voor het testen op basis van de 2020 dataset.  

Vraag is of alle data die in de 2020 versie zit ook uit Vesta te halen is. Of zijn er andere bronnen gebruikt en kunnen we die blijven gebruiken?

Voor de planning is het goed een overzicht te hebben van de kaartlagen die toegevoegd moeten worden met relatie naar Vesta items in configuratie.

**Comment by baasgeo** [comment]
De lijst met kaartlagen worden allemaal opgehaald via [https://ez.maps.arcgis.com/sharing/rest/search?(...)](https://ez.maps.arcgis.com/sharing/rest/search?) bij ArcGIS online. Ik heb een conversie gedaan van de json bestanden die worden gebruikt om de lijst met kaartlagen te krijgen.

[vesta_G.json.xlsx](https://github.com/user-attachments/files/16049627/vesta_G.json.xlsx)
[vesta_O.json.xlsx](https://github.com/user-attachments/files/16049628/vesta_O.json.xlsx)
[vesta_R.json.xlsx](https://github.com/user-attachments/files/16049630/vesta_R.json.xlsx)
[vesta_S.json.xlsx](https://github.com/user-attachments/files/16049631/vesta_S.json.xlsx)

Dit zou een eerste aanzet kunnen zijn om een overzicht te maken van de kaartlagen.

**Comment by eoudejans** [comment]
Wat betreft volgorde van belangrijkheid staan de gevoeligheidsanalyses onderaan, en hebben de algemene kaartlagen: gemeentegrenzen, buurtgrenzen, energielabels, aantal woningen meer prioriteit.

**Comment by MaartenHilferink** [comment]
Zie ook #18
