### ISSUE TITLE
Centrum gebieden vallen te snel weg.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#26]
In Friesland zijn er nogal wat CBS buurten die omringd worden door buitengebied. Bij uitzoomen vallen die (te) snel weg. Simplifyen is goed en moet beter, zie weer de steigertjes aan de kust , het havengebied van Makkum, en #16 en #24, maar hier lijkt de afval lat wel erg laag te liggen:

![image](https://github.com/ObjectVision/SAVI2/assets/2284361/9b1e0103-5c38-4c60-b787-5a7d95543af9)
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/c8b5fd44-eebe-4277-8ff0-baf6d2b28860)

**Comment by eoudejans** [comment]
Opgelost:
https://kaartviewer.asa2024.nl/app/map/main/101?center=5.5408945495905755;52.1390456302575&zoom=9&layerIds=219;110

![image](https://github.com/ObjectVision/SAVI2/assets/96182097/c60acde8-1923-4db6-8727-f9e069f34474)

Simplificatie op rdc_mm niveau leidde tot numerieke overflow bij area berekeningen en daarmee het wegvallen van centrum gebieden.
