### ISSUE TITLE
Mogelijkheden datamodel 2D vector tiles

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/SAVI2#27]
We zijn naar de optimale vorm aan het zoeken om de vector tegels aan MapGallery te leveren. Daar is ondermeer het volgende tussenresultaat voor gemaakt: https://kaartviewer.asa2024.nl/app/map/main/101?center=5.441446335640535;52.20578392566111&zoom=9&layerIds=219;110 waar simplificatie in extremen is toegepast en zoom niveaus 9 tot 11 geen attributen behalve een id bevatten:
![image](https://github.com/ObjectVision/SAVI2/assets/96182097/baa0a21f-148c-4eef-b169-f4bc68f1a4c1)

1. Samenvoegen van alle attributen op buurtniveau in 1 tabel maakt dat bijvoorbeeld zoom niveau 5 met 1 tegel voor heel Nederland alle attribuut data in zich heeft en op 5MB uit komt. Hier zouden we mee om kunnen gaan door per zoom niveau een afweging te maken welke attributen weggeschreven worden, @baasgeo ondersteunt MapGallery dit scenario?

2. Daarnaast vroegen we ons af of het mogelijk is om een kaartlaag op te bouwen uit meerdere tabellen, en per zoom niveau te specificeren welke tabel gebruikt wordt voor visualisaite, @baasgeo kan dit met de visualisatie stijl in MapGallery?

**Comment by MaartenHilferink** [comment]
De vraag is dus of een kaartlaag verschillend kan worden gedefinieerd voor verschillende zoom-levels, en met name met zoom-level specifieke TileJSON datasets kan hebben, aannemende dat een TileJSON dataset voor een aantal zoom-levels een set van attributen (kolommen) voor een set van rijen (entiteiten) representeert met zoom-level en tile specifieke geometrie en dat een kaartlaag voor een bepaald zoom-level alleen kan worden gedefinieerd o.b.v. aspecten uit dezelfde TileJSON dataset.

Voor lage zoom levels (<9) zijn kaartlaag specifieke TileJSON's optimaal (d.wz. << 5 MB), terwijl bij hoge zoom levels (>= 12) geometrie duplicatie besparing belangrijker is (dus veel attributen in een TileJSON).

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/74295a60-eb3f-41f9-b924-4053bcf5ef65)

**Comment by baasgeo** [comment]
>     1. Samenvoegen van alle attributen op buurtniveau in 1 tabel maakt dat bijvoorbeeld zoom niveau 5 met 1 tegel voor heel Nederland alle attribuut data in zich heeft en op 5MB uit komt. Hier zouden we mee om kunnen gaan door per zoom niveau een afweging te maken welke attributen weggeschreven worden, @baasgeo ondersteunt MapGallery dit scenario?
> 
>     2. Daarnaast vroegen we ons af of het mogelijk is om een kaartlaag op te bouwen uit meerdere tabellen, en per zoom niveau te specificeren welke tabel gebruikt wordt voor visualisaite, @baasgeo kan dit met de visualisatie stijl in MapGallery?

Je kunt in een vector tile meerdere layers specificeren, zo zijn de [BAG vector tiles](https://api.pdok.nl/lv/bag/ogc/v1_0) ook opgebouwd. Via de style geef je vervolgens aan hoe de kaartlagen getoond moet worden.

Voorbeeldje: [https://develop.mapgallery.eu/app/admin/layers/241/style](https://develop.mapgallery.eu/app/admin/layers/241/style)

Ook kun je bepaalde geometrie niet opnemen in een zoomlevel van een tile. Hoe dat technisch precies werkt weet ik niet precies.
