### ISSUE TITLE
Legenda te smal

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#29]
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/12630da8-bf26-4b13-b5bf-dfe818581819)

**Comment by baasgeo** [comment]
Is het een idee om de eenheid te verplaatsen van de titel naar de legenda en de nummering weg te halen? Dat geeft een  rustiger beeld en dan past de tekst prima in de legenda.

![Screen Shot 2024-07-03 at 15 42 48](https://github.com/ObjectVision/SAVI2/assets/1308903/ff7e230f-6fda-4d6c-a779-cd38ee86984f)

![Screen Shot 2024-07-03 at 15 45 11](https://github.com/ObjectVision/SAVI2/assets/1308903/5fff3c70-752f-47bd-a597-83e8834c4e72)

**Comment by MaartenHilferink** [comment]
en #35

**Comment by baasgeo** [comment]
Opgelost via #37
