### ISSUE TITLE
Feature request: i-tje bij legenda klassen

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/SAVI2#31]
![image](https://github.com/ObjectVision/SAVI2/assets/96182097/d3c6db58-6001-4e59-aa3e-989393d7d421)

**Comment by baasgeo** [comment]
Bij langere legenda titels geeft de applicatie een popover wanneer je met de muis erover hovert.

![Image](https://github.com/ObjectVision/SAVI2/assets/1308903/33948db8-399e-4181-935a-e1cac3f27e19)

Achter de i-knop is het mogelijk om metadata te tonen over de kaartlaag. Hier kunnen de klasses verder worden uitgelegd.

**Comment by MaartenHilferink** [comment]
Wordt niet geimplementeerd; workaraound: neem links per class op in kaartlaag-metainfo
