### ISSUE TITLE
Feature request: i-tje bij collections voor informatie over de specifieke collectie

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/SAVI2#32]
![image](https://github.com/ObjectVision/SAVI2/assets/96182097/50cfdccf-da48-486f-960c-7250ed6a2b5a)

**Comment by MaartenHilferink** [comment]
Not a defect. @eoudejans uitproberen voor S1 ... S5; bij voorkeur als url naar Strategie info van thematische site.

**Comment by MaartenHilferink** [comment]
Todo @baasgeo uitzoeken of plaatjes ipv symbolen mogelijk zijn, en met HREF ?
