### ISSUE TITLE
Borders van panden dunner maken (0 pixels bijvoorbeeld) bij beetje uitzoomen.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#33]
Voor de howto, zie #28

![image](https://github.com/ObjectVision/SAVI2/assets/2284361/7fc91cd7-f5f3-40a6-a298-886c4f6b9518)

Bij verder inzoomen is t wel al oké:
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/460a2c1e-d784-48f7-b5c5-f583eeb2ad8d)

**Comment by MaartenHilferink** [comment]
En natuurlijk helpt het ook als de pand geometrieën (verder) gesimplified worden, zie #34

**Comment by eoudejans** [comment]
Gerelateerd aan #28

**Comment by eoudejans** [comment]
Not working:
![Image](https://github.com/user-attachments/assets/28bd5527-b76d-430c-9406-fc079847f3b4)

**Comment by eoudejans** [comment]
Working:
![Image](https://github.com/user-attachments/assets/21e2d8ca-4eda-4ffc-b88d-aecea12a0313)
