### ISSUE TITLE
Feature request: Hiërarchische ordening van kaartlagen binnen een collectie, ook voor WZW

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#35]

**Comment by MaartenHilferink** [comment]
A la MapGallery classic

**Comment by baasgeo** [comment]
Dit is teruggekomen in een andere vorm, namelijk de bladwijzers. Hier kan een gebruiker zelf kaartlagen bewaren, sorteren en in een groep zetten. Dit wordt opgeslagen in het profiel van de gebruiker.

![Screen Shot 2024-07-03 at 15 53 26](https://github.com/ObjectVision/SAVI2/assets/1308903/5be15995-37af-4844-8898-aeba79f79764)
