### ISSUE TITLE
visualisatie gasnetten: pas aan bij meer inzoomen, en dan ook dikkere pijpen en kleuren obv ouderdom

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#36]
In SAWEC is meer gasnet data (deels leidingen, deels aansluitingen) te vinden:

![Image](https://github.com/ObjectVision/SAVI2/assets/2284361/a047003c-6499-46d7-86e7-e41e27641dd9)

**Comment by MaartenHilferink** [comment]
Deel van Overijssel ontbreekt; Brabant, Limburg en Paars zijn alleen aansluitpunten. 
Actie: t.b.v. de ASA2024 datalevering afstemmen welke bron(nen) we voor bestaande gasnetten-, en/of warmtenetten we gebruiken
en/of de door netbeheerder geleverde (en deels vanaf 2022 Buurt herverdeelde) capaciteitsgegevens per 2023 Buurt.

**Comment by eoudejans** [comment]
- [ ] Dikte zoomlevel afhankelijk
- [ ] Thematisch weergeven

**Comment by eoudejans** [comment]
See also #33

**Comment by MaartenHilferink** [comment]
![Image](https://github.com/user-attachments/assets/ee60e9bc-68cf-4ba7-82e9-ab3cb05c8eb5)

**Comment by MaartenHilferink** [comment]
Actie: Gasnet layer weghalen.

**Comment by MaartenHilferink** [comment]
closed as the latter action is a duplicate with #136
