### ISSUE TITLE
Unit in legenda onder de titel

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#37]

**Comment by MaartenHilferink** [comment]
See also #29

**Comment by eoudejans** [comment]
@MaartenHilferink @baasgeo initiele implementatie eenheden in legenda zie:

![Image](https://github.com/user-attachments/assets/23c65114-f9b4-47a3-a7ac-dcbff2cbad8f)

**Comment by baasgeo** [comment]
Ja mooi, zou de tekst wel links uitlijnen en dan een td colspan doen over de hele breedte van de tabel

**Comment by eoudejans** [comment]
@baasgeo 
![image](https://github.com/user-attachments/assets/ed03c291-7a7e-4b94-bd54-329082945ea1)

**Comment by baasgeo** [comment]
Top! Aandachtspunt hierbij is wel dat bij veel MapGalleries de 'name' attribuut is ingevuld met de kaartlaag naam. Het veld wordt nu niet gebruikt dus ook niet getoond in de legenda. Bij een update zou er dan ineens redundante tekst getoond worden.

De waarde zou dus bij een update van MapGallery gewist moeten worden. Iets van:
```
UPDATE layers SET geostyler = geostyler - 'name';
```

Daarnaast moet de _Genereer Style_ knop het attribuut ook niet meer vullen en zou de legenda preview in de beheer omgeving ook de Unit waarde moeten tonen. 

Het wel de vraag of dit veld zomaar leeg mag zijn. Dat zal ik onderzoeken.

**Comment by eoudejans** [comment]
Goede punten Bart, vooral dat bestaande kaartlagen met invulling voor het style.name veld ongewenste resultaten gaan vertonen. 

Over het style.name veld leeg laten, dat heb ik getest en gaat goed, style.name is dan een lege string.

**Comment by baasgeo** [comment]
Het update script is aangepast zodat bestaande gebruikers geen problemen zullen ondervinden. Deze aanpassing wordt meegenomen in de 7.2 release.
