### ISSUE TITLE
LN kaart toont onterecht Waterstof als oplossing voor buurten zonder bebouwing en/of doorrekening.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#40]
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/98554a96-adcd-4e13-b650-b1edf87ddd27)

![image](https://github.com/ObjectVision/SAVI2/assets/2284361/4df3a064-1a5d-4c2f-bab6-5eec5fb5bb8b)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/f7225749-cdd6-4d82-8852-3897f731dc49)

**Comment by eoudejans** [comment]
![image](https://github.com/ObjectVision/SAVI2/assets/96182097/ec709cf9-a734-4309-8cf0-6896a6cb8a14)
Opgelost, er was nog geen veld met onbebouwd in de LN kaartbladen. Zie bovenstaande screenshot
