### ISSUE TITLE
Bij uitzoomen vallen waddeneilanden (deels) weg.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#41]
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/ce158c59-e474-4093-88e3-53fcbc6d8288)

**Comment by MaartenHilferink** [comment]
Bij een tikje meer inzoomen zijn ze er weer:
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/ee2db49d-80cc-4433-9ecb-b501fd5d320e)

**Comment by eoudejans** [comment]
Dit heeft te maken met fine-tuning simplificatie op hogere zoomniveaus. De volgende update zal een verbeterde simplificatie afstelling hebben

**Comment by MaartenHilferink** [comment]
Misschien gaat het ook hier om het onderscheid tussen buitengrenzen (tussen buurt en zee of buitenland) en binnengrenzen, tussen 2 buurten, zie ook #22 . de buitengrenzen willen we een simpele variant zonder "steigertjes", maar dan wel vast houden. Binnengrenzen, en zelfs dorpskernen in friesland mogen bij uitzoomen wel verdwijnen, mits deze ruimte door een andere buurt wordt overgenomen. Ik kan in het simplify script de toepassing van de simplify factor afhankelijk maken van het aantal gebieden (1 of 2) dat aan een grenslijn raakt.

**Comment by eoudejans** [comment]
Related to #44

**Comment by eoudejans** [comment]
Simplificatie wat afgezwakt, waddeneilanden blijven nu bestaan: 
![Image](https://github.com/ObjectVision/SAVI2/assets/96182097/49a82fb6-4bd9-4fbe-983f-49552648b5d2)
