### ISSUE TITLE
Bij niet-extreem inzoomen vallen alle voorgrond kaartlagen weg; achtergrond blijft wel zichtbaar

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#42]
Hier nog wel alles:
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/ee13f4d1-c7ca-4ad6-88bc-e304e7402c2e)

Nu al weg:
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/bd1b3bc6-f721-4d62-abc0-6a4abd677272)

**Comment by eoudejans** [comment]
Twee oplossingen: 
- Blokkeer verder inzoomen dan gedefinieerd is
- Toevoegen extra zoomlevels

**Comment by eoudejans** [comment]
Zowel panden als data op buurtniveau gaan nu tot zoom niveau 18.
