### ISSUE TITLE
Kaartlaag zoeken op 2 characters werkt niet: 'LN', 'S1', 'R3'; wel werkt zoeken op: 'R19', 'R30', 'Laagste', etc.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#81]
![image](https://github.com/ObjectVision/SAVI2/assets/2284361/f1869f16-04d5-4631-876e-0f185db16f99)

**Comment by baasgeo** [comment]
De drempelwaarde ligt nu op 3 karakters voor het zoeken. Lijkt me prima om dit aan te passen naar 2 karakters.

**Comment by MaartenHilferink** [comment]
Nog oplossing bedenken voor PDOK adressen zoeken

**Comment by eoudejans** [comment]
Inmiddels werkt zoeken vanaf 2 characters
