### ISSUE TITLE
Improvement ideas for MapGallery landing page (collections overview)

### ISSUE THREAD

**Issue by eoudejans** [ObjectVision/SAVI2#82]

**Comment by eoudejans** [comment]
Current view ASA2024:
![image](https://github.com/user-attachments/assets/6d19e618-abe7-4332-a7eb-a5a6cc608e42)

**Comment by eoudejans** [comment]
Possible improvements using thumpnails:
![collections_thumpnails](https://github.com/user-attachments/assets/adfb3536-694b-4d09-922e-746a4cadb39d)

**Comment by eoudejans** [comment]
Further possible improvements:
- Add information (i) icon option to collections, which brings up a modal information dialog
- Add dropdown where user can select one of the available layers belonging to the collection

**Comment by eoudejans** [comment]
Als symbool veld eindigt op .png, .jpg, .jpeg toon dan plaatje, anders symbool.

**Comment by eoudejans** [comment]
Information button at colletions page:
![Image](https://github.com/user-attachments/assets/ce36dda9-1a74-41c5-9552-b995b58f023c)

Goed bekijken hoe de interacties werken bij klikken op collections tegel.

**Comment by baasgeo** [comment]
Kleine verbetering: logo wordt nu ook meegenomen in het klein bij de kaartview.

![Image](https://github.com/user-attachments/assets/8259e286-f080-473c-88b0-9116d382d9bd)
