### ISSUE TITLE
Bij niet ingelogd zijn geven doorgeappte links een leeg scherm.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#83]
![image](https://github.com/user-attachments/assets/241237bb-a3bc-4323-8e80-b18e1ace2a4f)

**Comment by MaartenHilferink** [comment]
Bij wel ingelogd zin werkte deze link wel:
https://kaartviewer.asa2024.nl/app/map/main/101?center=5.46155611088448;52.17494015446382&zoom=8&layerIds=212;110

**Comment by eoudejans** [comment]
Opgelost middels erafhalen inlog
