### ISSUE TITLE
Kaartlinks in de "Beschrijving kaartlaag" mogelijk maken (MapGallery?) en toepassen (ASA2024)

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#84]
H17 := H16 / H15

![image](https://github.com/user-attachments/assets/5330414a-611a-4c52-8a65-3f2918915433)

Het is erg wenselijk dat de in de beschrijving voorkomende H16 en H15 aanklikbaar zijn.

**Comment by MaartenHilferink** [comment]
En (bestaande) kaartlinks ik meta-info (gerelateerde kaartlagen) -> nieuw window bij aanklikken. Ik kijk nu niet voor niets naar S1 H17, en als ik de gerelateerde kaartlaag S2 H17 kies, zou er niet impliciet voor willen kiezen dat S1 H17 overschreven kan worden.

**Comment by eoudejans** [comment]
Links zijn toegevoegd en openen nu een nieuw window:
![image](https://github.com/user-attachments/assets/9b7d805c-705b-4b06-9018-dd4461dc1ca0)

**Comment by eoudejans** [comment]
Related to: https://github.com/ObjectVision/SAVI2/issues/87
