### ISSUE TITLE
Als ik ons kantoorpand aanklik (kaartlaag bouwjaar), krijgen alle panden een blauwe rand.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#85]
![image](https://github.com/user-attachments/assets/98b8b008-bddc-42ac-bf5d-454ab4bd5e98)

**Comment by MaartenHilferink** [comment]
De voorgenoemde beranding lijkt afhankelijk van het op dat moment actieve viewport:

![image](https://github.com/user-attachments/assets/2ebbddac-dc82-4fad-af27-4e5df64ab649)

**Comment by MaartenHilferink** [comment]
En blijven zelfs zichtbaar als de kaartlagen al weer buiten beeld zijn

![image](https://github.com/user-attachments/assets/f9b38e53-0420-42b3-97d1-d65e2b6aa2be)

**Comment by baasgeo** [comment]
Dit probleem ontstaat bij tilejson wanneer de dataset geen primary key (id) heeft. En polygon kan verspreid zijn over meerdere tiles, mapgallery maakt een selectie op basis van de huidige viewpoort en doet vervolgens een dissolve op de primary key om de juiste vlakken te selecteren.

Oplossing: voeg een primary key (id) toe aan de dataset.

**Comment by eoudejans** [comment]
Na toevoegen van id veld aan de pand laag gaat individuele pand selectie nu ook goed:
![image](https://github.com/user-attachments/assets/913351e4-3568-456f-b6c7-409ac8f7219e)

**Comment by eoudejans** [comment]
Verder gaat inzoomen voor de pandkaartlaag nu tot zoom 18.
