### ISSUE TITLE
Beschrijving H17 inconsistent met definitie H15

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#90]
H17 := H16 / H15 ?
H15 is niet gedefinieerd als de vermindering van CO2 uitstoot t.o.v. nu, maar enkel als de uitstoot straks, meestal 0.\
![image](https://github.com/user-attachments/assets/dd1b6d60-221a-4947-9034-4a29c93371d1)

**Comment by poorthuis-w** [comment]
![image](https://github.com/user-attachments/assets/2c449648-2fe6-4fb2-bfb6-b69a60d9f93d)

In de code in Vesta gaat dit wel goed. Daar wordt het verschil in nationale kosten (H16) gedeeld door het verschil in CO2-uitstoot (niet als hoofdindicator gerapporteerd). Het verschil in CO2-uitstoot is gedefinieerd als de huidige CO2-uistoot (niet als hoofdindicator gerapporteerd) minus de nieuwe CO2-uitstoot (H15). Dit lijkt me een documentatiefout.

**Comment by eoudejans** [comment]
Verbeterde definitie, nu consistent met rekenregel:
![Image](https://github.com/user-attachments/assets/d5321118-43a7-43cd-8b22-dbe574685afc)
