### ISSUE TITLE
Panden: Bouwjaar 2021 panden worden niet getoond (outline) maar wel selecteerbaar.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#91]
![image](https://github.com/user-attachments/assets/0f3f2bd9-bef5-446c-b3af-617f9b821f09)

![image](https://github.com/user-attachments/assets/53198317-1b99-49c8-8859-33322553aefc)

**Comment by eoudejans** [comment]
Panden waren er wel, maar de outline ontbrak zie:

![image](https://github.com/user-attachments/assets/d91aa859-a18e-4cf7-9ff6-90a64de02939)
