### ISSUE TITLE
Panden zijn niet up-to-date.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#92]
![image](https://github.com/user-attachments/assets/934cb45d-3f63-4699-ae11-b66324ae3ca4)

ref: OSM
![image](https://github.com/user-attachments/assets/e13c15b4-bae9-41fc-ad7f-3f5d33a21bc0)

**Comment by eoudejans** [comment]
Panden waren er wel, maar de outline ontbrak zie:

![image](https://github.com/user-attachments/assets/03ec0c1b-687c-4b3f-9509-5d9468bf2bd1)
