### ISSUE TITLE
Panden in Vesta lijken soms dubbel

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/SAVI2#93]
![image](https://github.com/user-attachments/assets/8a2f17fa-e7e2-4f03-b52d-32cd979c989d)

Aan het Revaleiland zijn panden van 2005 en 2018 of 2021 door elkaar heen getekend. Wat is de snapshotdatum ? Die 2005 panden zullen in de BAG toch wel gesloopt zijn>

**Comment by poorthuis-w** [comment]
Sourcedata: https://pbl.sliksvn.com/vesta/SD50_ASA
